resources:
  repositories:
  - repository: build
    type: github
    name: Haipa/build
    endpoint: public

extends:
  template: pipelines/templates/dotnetclient@build
  parameters:
    withCmdlet: true